##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [4.8.0-B50] date: [Thu Feb 26 18:45:43 CET 2026]
##########################################################################################################################

######################################
# target
######################################
TARGET = chip-tester
MAKEFLAGS += -j$(shell nproc)

######################################
# building variables
######################################
DEBUG = 1
OPT = -Og

#######################################
# paths
#######################################
BUILD_DIR = build

######################################
# source
######################################
C_SOURCES =  \
Core/Src/gpio.c \
Core/Src/quadspi.c \
Core/Src/stm32h7xx_it.c \
Core/Src/stm32h7xx_hal_msp.c \
Drivers/BSP/STM32H7xx_Nucleo/stm32h7xx_nucleo.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_cortex.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rcc.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rcc_ex.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_flash.c \
	Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_flash_ex.c \
	Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_gpio.c \
	Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_hsem.c \
	Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dma.c \
	Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dma_ex.c \
	Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_mdma.c \
	Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pwr.c \
	Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pwr_ex.c \
	Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal.c \
	Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_i2c.c \
	Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_i2c_ex.c \
	Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_exti.c \
	Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_qspi.c \
	Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_delayblock.c \
	Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_tim.c \
	Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_tim_ex.c \
	Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_usart.c \
	Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_usart_ex.c \
	Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_uart_ex.c \
	Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_uart.c \
	Core/Src/system_stm32h7xx.c \
	Core/Src/sysmem.c \
	Core/Src/syscalls.c \
	Core/Src/i2c.c \
	Core/Src/spi.c \
	Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_spi.c \
	Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_spi_ex.c \




	# ADDED: your C++ sources go here
	CPP_SOURCES = \
	Core/Src/protocols/i2cProtocol.cpp \
	Core/Src/protocols/spiProtocol.cpp \
	Core/Src/main.cpp


	ASM_SOURCES = startup_stm32h753xx.s
	ASMM_SOURCES =

	#######################################
	# binaries
	#######################################
	PREFIX = arm-none-eabi-
	ifdef GCC_PATH
CC  = $(GCC_PATH)/$(PREFIX)gcc
CXX = $(GCC_PATH)/$(PREFIX)g++   # ADDED
AS  = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP  = $(GCC_PATH)/$(PREFIX)objcopy
SZ  = $(GCC_PATH)/$(PREFIX)size
else
CC  = $(PREFIX)gcc
CXX = $(PREFIX)g++                # ADDED
AS  = $(PREFIX)gcc -x assembler-with-cpp
CP  = $(PREFIX)objcopy
SZ  = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S

#######################################
# CFLAGS
#######################################
CPU = -mcpu=cortex-m7
FPU = -mfpu=fpv5-d16
FLOAT-ABI = -mfloat-abi=hard
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

AS_DEFS =

# C defines
C_DEFS =  \
-DUSE_PWR_LDO_SUPPLY \
-DUSE_NUCLEO_144 \
-DUSE_HAL_DRIVER \
-DSTM32H753xx

AS_INCLUDES =
C_INCLUDES = \
-ICore/Inc \
-ICore/Inc/protocols \
-IDrivers/STM32H7xx_HAL_Driver/Inc \
-IDrivers/STM32H7xx_HAL_Driver/Inc/Legacy \
-IDrivers/BSP/STM32H7xx_Nucleo \
-IDrivers/CMSIS/Device/ST/STM32H7xx/Include \
-IDrivers/CMSIS/Include

ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

# ADDED: C++ flags - reuse CFLAGS, add C++-specific options
CXXFLAGS += $(CFLAGS) -std=c++17 -fno-exceptions -fno-rtti \
            -Wno-volatile \
            -Wno-int-to-pointer-cast \
            -Wno-pointer-to-int-cast

ifeq ($(DEBUG), 1)
CFLAGS   += -g -gdwarf-2
CXXFLAGS += -g -gdwarf-2
endif

CFLAGS   += -MMD -MP -MF"$(@:%.o=%.d)"
CXXFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"

#######################################
# LDFLAGS
#######################################
LDSCRIPT = STM32H753XX_FLASH.ld
LIBS = -lc -lm -lnosys
LIBDIR =
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin

#######################################
# build the application
#######################################
OBJECTS  = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))

# ADDED: C++ objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(CPP_SOURCES:.cpp=.o)))
vpath %.cpp $(sort $(dir $(CPP_SOURCES)))

OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASMM_SOURCES:.S=.o)))
vpath %.S $(sort $(dir $(ASMM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR)
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

# ADDED: rule for .cpp files
$(BUILD_DIR)/%.o: %.cpp Makefile | $(BUILD_DIR)
	$(CXX) -c $(CXXFLAGS) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@
$(BUILD_DIR)/%.o: %.S Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

# ADDED: link with g++ so C++ runtime is included
$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CXX) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@

$(BUILD_DIR):
	mkdir $@

clean:
	-rm -fR $(BUILD_DIR)

-include $(wildcard $(BUILD_DIR)/*.d)

upload: all
	openocd -f interface/stlink.cfg -f target/stm32h7x.cfg \
	  -c "program $(BUILD_DIR)/$(TARGET).elf verify reset exit"
